dataset:
  train:
    name: kandinsky_indoor_field
    disp_name: field_train
    dir: /share/data/p2p/zhiyanw/Indoor
    filenames: /share/data/p2p/zhiyanw/indoor_list.txt
    has_filled_depth: False
