dataset:
  train:
    name: kandinsky_indoor_OS
    disp_name: OS_train
    dir: /share/data/p2p/zhiyanw/Indoor_OS
    filenames: /share/data/p2p/zhiyanw/Indoor_OS_list.txt
    has_filled_depth: False
