dataset:
  train:
    name: kandinsky_indoor_field
    disp_name: field_train
    dir: /scratch/yz5880/Projective-Geometry-1024/Indoor_Real_1024
    filenames: /scratch/zhiyanw/Indoor_Real_1024.txt
    has_filled_depth: False
    promptlist: /scratch/yz5880/Projective-Geometry-1024/Indoor_Real_1024/captions_400k.json
